services:
  android:
    image: budtmo/docker-android-x86-8.1
    init: true
    container_name: android-container
    # userns_mode: host
    privileged: true
    ports: ['6080:6080', '5554:5554', '5555:5555', '4723:4723']
    scale: 1
    environment:
      - DEVICE=Nexus 5
      - APPIUM=true
      - SERVER_URL=${SERVER_URL:-http://web:4242}
    volumes:
      - work:/work
      # - .:/work
