name: CI for stripe-samples/accept-a-payment
on: [push, pull_request]

env:
  STRIPE_PUBLISHABLE_KEY: ${{ secrets.TEST_STRIPE_PUBLISHABLE_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.TEST_STRIPE_SECRET_KEY }}
  STRIPE_API_KEY: ${{ secrets.TEST_STRIPE_SECRET_KEY }}

jobs:
  e2e_android:
    # runs-on: ubuntu-20.04
    runs-on: macos-latest
    env:
      SERVER_URL: http://localhost:4242
      PRICE: ${{ secrets.TEST_PRICE }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: 'stripe-samples/sample-ci'
          path: 'sample-ci'
          ref: 'multiple-runtimes'

      - name: Setup dependencies
        run: |
          npm install -g appium
          appium -v
          appium &>/dev/null &

          curl -o- -L https://github.com/stripe/stripe-cli/releases/download/v1.7.0/stripe_1.7.0_mac-os_x86_64.tar.gz | tar fxz -
          sudo mv stripe /usr/local/bin/stripe

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 27
          script: .github/workflows/android_e2e.sh

      - name: Upload capybara screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: |
            tmp/
