name: CI for stripe-samples/accept-a-payment
on: [push, pull_request]

env:
  STRIPE_PUBLISHABLE_KEY: ${{ secrets.TEST_STRIPE_PUBLISHABLE_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.TEST_STRIPE_SECRET_KEY }}

jobs:
  e2e_test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        implementation:
          - client_type: html
            server_url: http://web:4242
    env:
      SERVER_URL: ${{ matrix.implementation.server_url }}
      COMPOSE_FILE: docker-compose.yml:docker-compose.android.yml
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: 'stripe-samples/sample-ci'
          path: 'sample-ci'
          ref: 'multiple-runtimes'

      - name: Setup dependencies
        run: |
          source sample-ci/helpers.sh
          setup_dependencies

      - name: aoeu
        run: |
          sudo apt install cpu-checker
          sudo kvm-ok

      - name: Run tests
        run: |
          source sample-ci/helpers.sh

          install_docker_compose_settings
          export STRIPE_WEBHOOK_SECRET=$(retrieve_webhook_secret)
          cat <<EOF >> .env
          DOMAIN=${{ matrix.implementation.server_url }}
          PRICE=${{ secrets.TEST_PRICE }}
          PAYMENT_METHOD_TYPES="card"
          EOF

          configure_docker_compose_for_integration custom-payment-flow node ../../client/${{ matrix.implementation.client_type }} node:14.17
          docker-compose up -d && wait_web_server
          sleep 500
          docker-compose exec -T android bash -c "cd /work/custom-payment-flow/client/android-kotlin && ./gradlew installDebug"
          command="docker-compose exec -T runner bundle exec rspec spec/custom_payment_flow_android_spec.rb"
          $command \
            || $command --only-failures \
            || $command --only-failures --format RSpec::Github::Formatter --format progress

      - name: Collect debug information
        if: ${{ failure() }}
        run: |
          cat .env
          cat docker-compose.yml
          docker-compose ps -a
          docker-compose logs android
          docker-compose logs web

          docker cp $(docker-compose ps -qa runner | head -1):/work/tmp .

      - name: Upload capybara screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: |
            tmp/capybara
