name: CI for stripe-samples/accept-a-payment
on: [push, pull_request]

env:
  STRIPE_PUBLISHABLE_KEY: ${{ secrets.TEST_STRIPE_PUBLISHABLE_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.TEST_STRIPE_SECRET_KEY }}

jobs:
  e2e_android:
    # runs-on: ubuntu-20.04
    runs-on: macos-latest
    env:
      SERVER_URL: http://localhost:4242
      PRICE: ${{ secrets.TEST_PRICE }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: 'stripe-samples/sample-ci'
          path: 'sample-ci'
          ref: 'multiple-runtimes'

      - name: Docker
        run: |
          # brew install homebrew/cask
          # brew cask install docker-toolbox
          brew install docker-toolbox

          # create the docker machine
          # docker-machine create --driver "virtualbox" default

          # start the docker machine
          # docker-machine start default

          # this command allows the docker commands to be used in the terminal
          eval "$(docker-machine env default)"

          docker run hello-world
