name: CI for stripe-samples/accept-a-payment
on: [push, pull_request]

env:
  STRIPE_PUBLISHABLE_KEY: ${{ secrets.TEST_STRIPE_PUBLISHABLE_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.TEST_STRIPE_SECRET_KEY }}

jobs:
  e2e_android:
    # runs-on: ubuntu-20.04
    runs-on: macos-latest
    env:
      SERVER_URL: http://localhost:4242
      PRICE: ${{ secrets.TEST_PRICE }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: 'stripe-samples/sample-ci'
          path: 'sample-ci'
          ref: 'multiple-runtimes'
